In [2]:
import torch
import pickle
from argparse import ArgumentParser
import os
from trainer import Trainer
from config import Config
import json
import sys

In [3]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [4]:
import torch.nn as nn
from torchvision.models import resnet101

base_model = resnet101(pretrained= True, progress= False)   # Encoder의 backbone model은 resnet101
base_model = list(base_model.children())[:-2]               # 마지막 2개의 layer는 제거 (추론기)
resnet = nn.Sequential(*base_model)                    # resnet은 Sequential 객체

print(type(resnet))
print(resnet)


C:\Users\ihman\AppData\Roaming\Python\Python310\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\ihman\AppData\Roaming\Python\Python310\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


<class 'torch.nn.modules.container.Sequential'>
Sequential(
  (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace=True)
  (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (4): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256,

In [40]:
m = nn.Linear(3, 3)
m.weight.data.fill_(0)
print(m.weight.data)
m.bias.data.fill_(0)
print('-'*5, 'bias', '-'*5)
print(m.bias)
print(m.bias.data)

print('-'*5, 'weight', '-'*5)
m.weight.data.uniform_(0, 10)
#print(m.weight)
print(m.weight.data)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
----- bias -----
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([0., 0., 0.])
----- weight -----
tensor([[3.3599, 4.1950, 2.8951],
        [4.0242, 7.7427, 3.4391],
        [0.9190, 6.6122, 5.1698]])
